name: Build Mbed CE Arduino Cores

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build_cores:
    strategy:
      matrix:
        mbed_target:
          - ARDUINO_NANO33BLE
          - RASPBERRY_PI_PICO
          - ARDUINO_NICLA_SENSE_ME
        cmake_build_type:
          - Debug
          - Release

    runs-on: ubuntu-latest
    container: ghcr.io/armmbed/mbed-os-env:master-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Python Venv
        run: |
          apt-get update
          apt-get install -y python3-venv

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -GNinja -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }} -DMBED_TARGET=${{ matrix.mbed_target }} -DUPLOAD_METHOD=NONE -DCMAKE_INSTALL_PREFIX=$(pwd)/../install
          ninja
          ninja package

      - name: Archive Core Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Arduino Core ${{ matrix.mbed_target }} ${{ matrix.cmake_build_type }} (Zip)
          path: build/ArduinoCore-mbed-ce-*.zip