name: Build Mbed CE Arduino Cores

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build_cores:
    strategy:
      matrix:
        mbed_target:
          - ARDUINO_NANO33BLE
          - RASPBERRY_PI_PICO
        cmake_build_type:
          - Debug
          - Release

    runs-on: ubuntu-latest
    container: ghcr.io/armmbed/mbed-os-env:master-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
  
      - name: Install Python Dependencies
        run: |
          # Note: The Mbed container is too old to have python3-json5, but it's old enough that we can
          # still install python packages globally.
          # On newer Ubuntu versions, you would instead use:
          # apt-get update
          # xargs apt-get install -y < mbed-os/tools/requirements.apt.txt
          
          python3 -m pip install -r  mbed-os/tools/requirements.txt
      
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -GNinja -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }} -DMBED_TARGET=${{ matrix.mbed_target }} -DUPLOAD_METHOD=NONE -DCMAKE_INSTALL_PREFIX=$(pwd)/../install
          ninja
          ninja package
