name: Publish Artifacts on Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write


# This workflow run fires whenever a tag is created, and downloads all compiled cores and publishes them
# as part of the release.
# It does have one limitation: you have to manually ensure this workflow gets run after all the build-core
# workflow runs are completed.  I couldn't find a way to make it wait automatically.

jobs:
  release:
    name: Create Release with Artifacts
    runs-on: ubuntu-latest
    steps:
#      - name: Show GitHub context
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#        run: echo "$GITHUB_CONTEXT"

      - name: Download All Compiled Core Artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build-cores.yml
          commit: ${{ github.sha }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          files: |
            **/*.zip