name: Publish Artifacts on Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write

jobs:
  release:
    name: Create Release with Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Download All Compiled Core Artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          commit: ${{ github.sha }}