name: Publish Artifacts on Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write

jobs:
  release:
    name: Create Release with Artifacts
    runs-on: ubuntu-latest
    steps:
#      - name: Show GitHub context
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#        run: echo "$GITHUB_CONTEXT"

      - name: Download All Compiled Core Artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build-cores.yml
          commit: ${{ github.sha }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          files: |
            **/*.zip